"""fix post model schema

Revision ID: 7cf534abe9db
Revises: af0eed06efcd
Create Date: 2024-06-10 22:23:48.404462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf534abe9db'
down_revision = 'af0eed06efcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_embed', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
        batch_op.drop_column('image_filename')
        batch_op.drop_column('image_data')
        batch_op.drop_column('visible')
        batch_op.drop_column('map_embed')

    op.create_table('_alembic_tmp_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('transit', sa.VARCHAR(length=64), nullable=False),
    sa.Column('neighbourhood', sa.VARCHAR(length=64), nullable=False),
    sa.Column('beer_rating', sa.INTEGER(), nullable=False),
    sa.Column('guinness', sa.BOOLEAN(), nullable=False),
    sa.Column('smoking', sa.BOOLEAN(), nullable=False),
    sa.Column('music', sa.VARCHAR(length=128), nullable=False),
    sa.Column('map_embed', sa.TEXT(), nullable=False),
    sa.Column('visible', sa.BOOLEAN(), nullable=False),
    sa.Column('image_data', sa.BLOB(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
