"""updated post fields

Revision ID: af0eed06efcd
Revises: 6f4c21ff4596
Create Date: 2024-06-05 21:43:15.903049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0eed06efcd'
down_revision = '6f4c21ff4596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('transit', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('neighbourhood', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('beer_rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('guinness', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('smoking', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('music', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('music')
        batch_op.drop_column('smoking')
        batch_op.drop_column('guinness')
        batch_op.drop_column('beer_rating')
        batch_op.drop_column('neighbourhood')
        batch_op.drop_column('transit')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
